FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
COPY fastapp/ /app/fastapp/
ENV MONGODB_URI=placeholder
ENV MONGODB_DATABASE=placeholder
ENV MONGO_KEY=placeholder
ENV ADMIN_USER=placeholder
ENV GOOGLE_CLOUD_PROJECT_ID=placeholder
ENV GCP_REGION=placeholder
ENV GCS_BUCKET_NAME=placeholder
ENV GOOGLE_API_KEY=placeholder
ENV GOOGLE_CLIENT_ID=placeholder
ENV GOOGLE_CLIENT_SECRET=placeholder
ENV GOOGLE_REDIRECT_URI=placeholder
ENV JWT_SECRET_KEY=placeholder
ENV GCP_DEFAULT_ZONE=placeholder
ENV BIHAND_PUBLIC_API_URL=placeholder
ENV STICKER_TOOL_BASE_URL=https://sticker-generator.graphicsminer.com
ENV VERSION=placeholder
ENV LOG_LEVEL=INFO
ENV ENV=prod
ENV PORT=8501
ENV REDIS_URL=placeholder
ENV STRIPE_SECRET_KEY=placeholder
ENV STRIPE_WEBHOOK_SECRET=placeholder
RUN mkdir -p /app/logs
CMD ["celery", "-A", "fastapp.celery_app", "worker", "--loglevel=info"]