import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'vi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, defaultValue?: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Landing Page
    'landing.now_supporting': 'Now supporting Claude Code & OpenClaw',
    'landing.title_1': 'Hire Your First',
    'landing.title_2': 'Autonomous Employee Fleet',
    'landing.subtitle': 'Create your zero-human business setup in 1 click. Bihand spins up secure Google Cloud VMs, deploys fully-equipped AI employee agents, and establishes live web browsers so you can watch them execute your goals. Fast, secure, and ready to work for you 24/7.',
    'landing.go_to_dashboard': 'Go to Dashboard',
    'landing.sign_in': 'Sign In',
    'landing.sign_out': 'Sign Out',
    'landing.features.title': 'Features',
    'landing.features.multi_agent.title': 'Multi-Agent Hierarchies',
    'landing.features.multi_agent.desc': 'Build true organizational charts. Assign a CEO to plan the roadmap, a PM to write tickets, and multiple Developers to execute them in parallel.',
    'landing.features.native_app.title': 'Native App Integrations',
    'landing.features.native_app.desc': 'Seamlessly authenticate with Google Workspace via secure OAuth. Your agents can instantly read emails, manage calendars, and edit Google Docs.',
    'landing.features.live_screens.title': 'Live Virtual Screens',
    'landing.features.live_screens.desc': 'Never wonder what your agents are doing. Open a secure NoVNC stream to watch them click, type, and navigate browsers in real-time.',
    'landing.features.secure_sandboxing.title': 'Secure Sandboxing',
    'landing.features.secure_sandboxing.desc': 'Every agent runs in a dedicated, isolated VM on Google Cloud. Your credentials are AES-256 encrypted at rest.',
    'landing.features.cli_first.title': 'CLI First',
    'landing.features.cli_first.desc': "Bring your own agent logic. We natively support OpenClaw and Anthropic's Claude Code out of the box, with full terminal access.",
    'landing.features.model_agnostic.title': 'Model Agnostic',
    'landing.features.model_agnostic.desc': 'Plug and play any model. Use GPT-4o for complex reasoning, Claude 3.5 Sonnet for coding, or Gemini 1.5 Pro for massive context windows.',
    'landing.features.section_title': 'Everything you need to run an AI workforce',
    'landing.tagline': 'Chat, assign, and watch your agents get to work.',
    'landing.get_started': 'Get Started Free',
    'landing.demo.title': 'Deploy your first AI fleet',
    'landing.demo.subtitle': 'Takes less than a minute.',
    'landing.cta_band.title': 'Ready to build your AI workforce?',
    'landing.cta_band.subtitle': 'Set up your first fleet in under a minute — no infrastructure to manage.',
    'landing.cta_band.button': 'Deploy your fleet',
    'landing.stats.agents': 'AI agents deployed',
    'landing.stats.fleets': 'Fleets running',
    'landing.stats.runtimes': 'Agent runtimes supported',
    'landing.stats.uptime': 'Platform uptime',
    'landing.showcase.title': 'See your agents actually work',
    'landing.showcase.subtitle': 'Real conversations, real hierarchies, real output — not just another dashboard.',
    'landing.showcase.chat.label': 'Live task chat',
    'landing.showcase.chat.user': 'Find 3 new AI competitors that launched this quarter and summarize their pricing.',
    'landing.showcase.chat.agent_1': "On it — pulling live data from the web and our CRM.",
    'landing.showcase.chat.step_1': 'Scraped pricing from 3 competitor sites',
    'landing.showcase.chat.step_2': 'Cross-referenced with market research notes',
    'landing.showcase.chat.step_3': 'Drafting comparison report...',
    'landing.showcase.chat.artifact': 'competitor-pricing-Q3.md ready',
    'landing.showcase.org.label': 'Multi-agent hierarchy',
    'landing.showcase.org.ceo': 'CEO Agent',
    'landing.showcase.org.pm': 'PM Agent',
    'landing.showcase.org.dev': 'Developer Agent',
    'landing.showcase.org.marketing': 'Marketing Agent',
    'landing.showcase.org.status': 'online',
    'landing.showcase.example_label': 'Real-world example',
    'landing.showcase.mock.backlog': 'Backlog',
    'landing.showcase.mock.in_progress': 'In Progress',
    'landing.showcase.mock.done': 'Done',
    'landing.showcase.mock.ticket': 'Fix login bug',
    'landing.showcase.mock.ticket_2': 'Update pricing page',
    'landing.showcase.mock.delegation_log': 'CEO Agent delegated "Fix login bug" to Developer Agent · 2m ago',
    'landing.showcase.mock.connected': 'Connected',
    'landing.showcase.mock.integrations_log': 'Agent read 3 new emails, scheduled 1 meeting',
    'landing.showcase.mock.live_label': 'LIVE — Chris (Sales Agent) filling out CRM form',
    'landing.showcase.mock.vault': 'AES-256 Encrypted Vault',
    'landing.features.multi_agent.example': "When the CTO Agent blocks a ticket, it auto-reassigns to the next available Developer Agent — no stand-up required.",
    'landing.features.native_app.example': "Ask your PM Agent to draft the sprint doc — it reads your calendar, drafts in Google Docs, and shares it with the team automatically.",
    'landing.features.live_screens.example': "Watch your Sales Agent fill out a CRM form live in your browser — pause, take over, or let it keep going.",
    'landing.features.secure_sandboxing.example': "Every agent's OS, credentials, and files live in their own hardware-isolated VM — nothing shared, nothing leaked.",
    'landing.features.cli_first.example': "Bring your own harness — Claude Code or OpenClaw boots with full terminal and git access on day one.",
    'landing.features.model_agnostic.example': "Route reasoning-heavy planning to Claude 3.5 Sonnet, and bulk classification to a faster model — per agent, per task.",
    'landing.footer': '© 2026 Bihand. Open-Source AI Workforces.',

    // Sidebar & Navigation
    'nav.select_company': 'Select a Fleet',
    'nav.your_companies': 'Your Fleets',
    'nav.incorporate_new': 'Deploy New Fleet',
    'nav.dashboard': 'Dashboard',
    'nav.inbox': 'Inbox',
    'nav.org_chart': 'Org Chart',
    'nav.goals_roadmap': 'Goals & Roadmap',
    'nav.incidents': 'Incidents & Issues',
    'nav.scheduled_routines': 'Scheduled Routines',
    'nav.audit_logs': 'Audit Logs',
    'nav.usage_costs': 'Usage & Costs',
    'nav.infrastructure': 'Infrastructure',
    'nav.agents': 'Agents (Employees)',
    'nav.platform': 'Platform',
    'nav.credentials': 'Credentials',
    'nav.billing_packages': 'Billing & Packages',
    'nav.admin_panel': 'Admin Panel',
    'nav.sign_out': 'Sign Out',
    'nav.workspace': 'Workspace',
    'nav.architecture_studio': 'Architect Studio',
    'nav.film_studio': 'Film Studio',
    'nav.trading_studio': 'Trading Studio',
    'nav.exit_to_portal': 'Exit to Portal',
    'nav.loading': 'Loading...',
    'nav.no_fleets_found': 'No fleets found',

    // Incorporate Wizard
    'wizard.title': 'Deploy an AI Fleet',
    'wizard.subtitle': 'Configure your cloud fleet infrastructure, assign agent roles, and deploy instances.',
    'wizard.step_1': 'Fleet & Mission',
    'wizard.step_2': 'Fleet Configuration',
    'wizard.step_3': 'First Task',
    'wizard.step_4': 'Review & Password',
    'wizard.company_name': 'Fleet Name',
    'wizard.company_domain': 'Fleet Domain',
    'wizard.mission_statement': 'Fleet Mission Statement',
    'wizard.mission_placeholder': 'Describe what your AI fleet will do...',
    'wizard.next': 'Next Step',
    'wizard.previous': 'Previous',
    'wizard.incorporating': 'Deploy Fleet',
    'wizard.monthly_budget': 'Monthly API Budget',
    'wizard.initial_task_title': 'Initial Task Title',
    'wizard.initial_task_desc': 'Initial Task Description',
    'wizard.password': 'Master Password',
    'wizard.password_placeholder': 'Set secure dashboard password',
    'wizard.summary_review': 'Review & Launch',

    // Login Page
    'login.title': 'Sign In to Bihand',
    'login.subtitle': 'Enter your credentials to manage your AI workforce.',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.button': 'Sign In',
    'login.no_account': "Don't have an account? Complete the deployment flow on the home page.",

    // Dashboard General
    'dashboard.title': 'Your Fleets',
    'dashboard.subtitle': 'Deploy, scale, and manage your cloud fleets of autonomous agents.',
    'dashboard.status.running': 'Running',
    'dashboard.status.provisioning': 'Provisioning',
    'dashboard.status.stopped': 'Stopped',
    'dashboard.no_fleets': 'No active fleets. Start by deploying your first fleet.',
    'dashboard.no_companies_found': 'No Fleets Found',
    'dashboard.no_companies_desc': "You haven't deployed any fleets yet. Click below to spin up your first fleet of autonomous agents.",

    // Additional translations
    'fleet.org_chart.title': 'Org Chart',
    'fleet.org_chart.subtitle': 'View how AI agents collaborate and report tasks to each other.',
    'fleet.issues.title': 'Incidents & Issues',
    'fleet.issues.subtitle': 'Create tasks or check which AI agent is working on issues.',
    'fleet.activity.title': 'Live Activity',
    'fleet.activity.subtitle': 'Monitor real-time agent thoughts and execution logs.',
    'fleet.costs.title': 'Usage & Costs',
    'fleet.costs.subtitle': 'Track VM hosting and global API spend for your fleet.',
    'fleet.costs.infra_burn': 'Infra Burn',
    'fleet.costs.api_spend': 'API Spend',
    'fleet.costs.limit': 'Limit',
    
    // SANT Arch Studio
    'arch.title': 'Architect Studio',
    'arch.subtitle': 'State-of-the-art AI architectural rendering, interior renovation, and walkthrough video creation suite.',
    'arch.balance': 'Bihand Wallet',
    'arch.rendered_image': 'Workspace Canvas Preview',
    'arch.rendering_ready': 'Ready for AI Rendering',
    'arch.rendering_ready_desc': 'Upload an image or select a model to start',
    'arch.start_render': 'Start Render',
    'arch.back': 'Back',
    'arch.sketch': '1. Upload Sketch / Image',
    'arch.sketch_desc': 'Supports PNG, JPG, JPEG',
    'arch.add_sketch': 'Add Sketch Image',
    'arch.prompt': 'Describe Idea (Prompt):',
    'arch.prompt_placeholder': 'Type what you want to generate...',
    'arch.details': '3. Detailed Options',
    'arch.building_type': 'Building Type:',
    'arch.style': 'Rendering Quality Style:',
    'arch.aspect_ratio': 'Aspect Ratio',
    'arch.negative_prompt': 'Negative Prompt',
    'arch.history': 'Recent Renders History',
    'arch.no_history': 'No renders in history yet.',
    'arch.load_more': 'Load more history',
    'arch.submitting': 'Submitting request...',

    // Film Studio
    'film.title': 'Film Studio',
    'film.subtitle': 'Exquisite multi-panel storyboards, cinematic video vlogs, physics animations, art renders, and voice narratives.',
    'film.start_film': 'Start Filmmaking',
    'film.submitting': 'Generating film...',
    'film.create_project': 'Create New Project',
    'film.project_name': 'Project Name',
    'film.wallet': 'Wallet',
    'film.empty_project': 'You have not initialized any film editing projects yet.',
    'film.create_first': 'Create First Project',
    'film.delete_project': 'Delete Project',
    'film.nodes': 'Timeline Nodes',
    'film.untitled': 'Untitled Project',
    'film.history_title': 'Generated History & AI Templates',
    'film.use_template': 'Use AI Template',
    'film.open_project': 'Open Project',
    'film.no_history': 'No completed generations found. Create a new project and import AI assets to start!',
    'film.cost': 'Cost',
    'film.quick_video_gen': 'Quick AI Video Gen',
    'film.import_title': 'Smart AI Generation Import',
    'film.add_sketch': 'Sketch Reference Image (Optional):',
    'film.add_ref': 'Add reference',
    'film.prompt_label': 'Script / Storyboard Idea (Prompt):',
    'film.style_label': 'Art Style:',
    'film.aspect_ratio_label': 'Aspect Ratio:',
    'film.voice_label': 'AI Narrator Voice:',
    'film.locale_label': 'Language Code:',
    'film.sections_label': 'Number of Scenes to Insert:',
    'film.cancel': 'Cancel',
    'film.confirm_import': 'Confirm New Import',
    'film.choose_from_history': 'Choose assets from AI History (History Bank)',
    'film.import_all': 'Import All',
    'film.empty_history_desc': 'Your asset history is currently empty. Start generating new clips using the panel on the left!',
    
    // Tab translations (English)
    'film.tab.comic': 'Comic Book Storyboard',
    'film.tab.vlog': 'Vlog & Cinematic Video',
    'film.tab.manim': 'Manim Maths Animator',
    'film.tab.image': 'Art & Vector Generation',
    'film.tab.sound': 'Sound Effects & TTS',
    
    'arch.tab.render_img': 'Render Image',
    'arch.tab.render_plan': 'Render Floorplan',
    'arch.tab.renovate': 'AI Renovation',
    'arch.tab.view_sync': 'View Sync'
  },
  vi: {
    // Landing Page
    'landing.now_supporting': 'Hiện đang hỗ trợ Claude Code & OpenClaw',
    'landing.title_1': 'Thuê Đội Ngũ Nhân Viên AI',
    'landing.title_2': 'Làm Việc Tự Động Cho Bạn',
    'landing.subtitle': 'Tạo doanh nghiệp không bóng dáng con người chỉ với 1 click. Bihand tự động khởi tạo máy ảo Google Cloud siêu bảo mật, triển khai nhân viên AI chuyên nghiệp và thiết lập màn hình trình duyệt trực tiếp để bạn theo dõi họ hoàn thành công việc của mình liên tục 24/7.',
    'landing.go_to_dashboard': 'Đến Trang Điều Khiển',
    'landing.sign_in': 'Đăng Nhập',
    'landing.sign_out': 'Đăng Xuất',
    'landing.features.title': 'Tính năng',
    'landing.features.multi_agent.title': 'Hệ Thống Phân Cấp Đa Tác Nhân',
    'landing.features.multi_agent.desc': 'Xây dựng sơ đồ tổ chức thực tế. Chỉ định CEO lập lộ trình, PM viết nhiệm vụ và nhiều Nhà phát triển thực thi song song.',
    'landing.features.native_app.title': 'Tích Hợp Ứng Dụng Gốc',
    'landing.features.native_app.desc': 'Xác thực liền mạch với Google Workspace qua OAuth an toàn. Tác nhân có thể đọc email, quản lý lịch và sửa tài liệu ngay lập tức.',
    'landing.features.live_screens.title': 'Màn Hình Ảo Trực Tiếp',
    'landing.features.live_screens.desc': 'Không bao giờ phải tò mò tác nhân đang làm gì. Mở luồng NoVNC an toàn để xem họ click, gõ phím và duyệt web thời gian thực.',
    'landing.features.secure_sandboxing.title': 'Hộp Cát Bảo Mật',
    'landing.features.secure_sandboxing.desc': 'Mỗi tác nhân chạy trên một máy ảo chuyên dụng, cô lập trên Google Cloud. Thông tin đăng nhập được mã hóa AES-256 khi lưu trữ.',
    'landing.features.cli_first.title': 'Ưu Tiên Giao Diện Dòng Lệnh',
    'landing.features.cli_first.desc': 'Mang theo tư duy tác nhân riêng của bạn. Chúng tôi hỗ trợ sẵn OpenClaw và Claude Code của Anthropic với quyền truy cập terminal đầy đủ.',
    'landing.features.model_agnostic.title': 'Không Phụ Thuộc Vào Mô Hình',
    'landing.features.model_agnostic.desc': 'Cắm và chạy bất kỳ mô hình nào. Dùng GPT-4o cho lập luận phức tạp, Claude 3.5 Sonnet để lập trình, hoặc Gemini 1.5 Pro cho ngữ cảnh khổng lồ.',
    'landing.features.section_title': 'Mọi thứ bạn cần để vận hành đội ngũ AI',
    'landing.tagline': 'Trò chuyện, giao việc, và xem tác nhân của bạn bắt tay vào làm.',
    'landing.get_started': 'Bắt đầu miễn phí',
    'landing.demo.title': 'Triển khai hạm đội AI đầu tiên của bạn',
    'landing.demo.subtitle': 'Chỉ mất chưa đầy một phút.',
    'landing.cta_band.title': 'Sẵn sàng xây dựng đội ngũ AI của bạn?',
    'landing.cta_band.subtitle': 'Thiết lập hạm đội đầu tiên trong chưa đầy một phút — không cần quản lý hạ tầng.',
    'landing.cta_band.button': 'Triển khai hạm đội',
    'landing.stats.agents': 'Tác nhân AI đã triển khai',
    'landing.stats.fleets': 'Hạm đội đang hoạt động',
    'landing.stats.runtimes': 'Hệ tác nhân hỗ trợ',
    'landing.stats.uptime': 'Thời gian hoạt động',
    'landing.showcase.title': 'Xem tác nhân của bạn thực sự làm việc',
    'landing.showcase.subtitle': 'Hội thoại thực, cấu trúc tổ chức thực, kết quả thực — không chỉ là một bảng điều khiển.',
    'landing.showcase.chat.label': 'Trò chuyện công việc trực tiếp',
    'landing.showcase.chat.user': 'Tìm 3 đối thủ AI mới ra mắt trong quý này và tóm tắt giá của họ.',
    'landing.showcase.chat.agent_1': 'Đã nhận — đang lấy dữ liệu trực tiếp từ web và CRM của chúng ta.',
    'landing.showcase.chat.step_1': 'Đã thu thập giá từ 3 trang đối thủ',
    'landing.showcase.chat.step_2': 'Đã đối chiếu với ghi chú nghiên cứu thị trường',
    'landing.showcase.chat.step_3': 'Đang soạn báo cáo so sánh...',
    'landing.showcase.chat.artifact': 'competitor-pricing-Q3.md đã sẵn sàng',
    'landing.showcase.org.label': 'Cấu trúc đa tác nhân',
    'landing.showcase.org.ceo': 'Tác Nhân CEO',
    'landing.showcase.org.pm': 'Tác Nhân PM',
    'landing.showcase.org.dev': 'Tác Nhân Developer',
    'landing.showcase.org.marketing': 'Tác Nhân Marketing',
    'landing.showcase.org.status': 'trực tuyến',
    'landing.showcase.example_label': 'Ví dụ thực tế',
    'landing.showcase.mock.backlog': 'Việc cần làm',
    'landing.showcase.mock.in_progress': 'Đang thực hiện',
    'landing.showcase.mock.done': 'Hoàn thành',
    'landing.showcase.mock.ticket': 'Sửa lỗi đăng nhập',
    'landing.showcase.mock.ticket_2': 'Cập nhật trang giá',
    'landing.showcase.mock.delegation_log': 'Tác Nhân CEO đã giao "Sửa lỗi đăng nhập" cho Tác Nhân Developer · 2 phút trước',
    'landing.showcase.mock.connected': 'Đã kết nối',
    'landing.showcase.mock.integrations_log': 'Tác nhân đã đọc 3 email mới, lên lịch 1 cuộc họp',
    'landing.showcase.mock.live_label': 'TRỰC TIẾP — Chris (Tác Nhân Sales) đang điền form CRM',
    'landing.showcase.mock.vault': 'Kho Mã Hóa AES-256',
    'landing.features.multi_agent.example': 'Khi Tác Nhân CTO chặn một ticket, nó tự động giao lại cho Tác Nhân Developer tiếp theo đang rảnh — không cần họp stand-up.',
    'landing.features.native_app.example': 'Yêu cầu Tác Nhân PM soạn tài liệu sprint — nó đọc lịch của bạn, soạn thảo trong Google Docs, và tự động chia sẻ với cả đội.',
    'landing.features.live_screens.example': 'Xem Tác Nhân Sales điền form CRM trực tiếp ngay trên trình duyệt của bạn — tạm dừng, tiếp quản, hoặc để nó tiếp tục.',
    'landing.features.secure_sandboxing.example': 'Hệ điều hành, thông tin đăng nhập và tệp tin của mỗi tác nhân đều nằm trong máy ảo cô lập phần cứng riêng — không chia sẻ, không rò rỉ.',
    'landing.features.cli_first.example': 'Mang theo công cụ riêng của bạn — Claude Code hoặc OpenClaw khởi động với đầy đủ quyền truy cập terminal và git ngay từ ngày đầu.',
    'landing.features.model_agnostic.example': 'Định tuyến lập kế hoạch phức tạp cho Claude 3.5 Sonnet, và phân loại hàng loạt cho một mô hình nhanh hơn — theo từng tác nhân, từng tác vụ.',
    'landing.footer': '© 2026 Bihand. Lực Lượng Lao Động AI Nguồn Mở.',

    // Sidebar & Navigation
    'nav.select_company': 'Chọn Hạm Đội',
    'nav.your_companies': 'Hạm Đội Của Bạn',
    'nav.incorporate_new': 'Triển Khai Hạm Đội Mới',
    'nav.dashboard': 'Trang Điều Khiển',
    'nav.inbox': 'Hộp Thư Đến',
    'nav.org_chart': 'Sơ Đồ Tổ Chức',
    'nav.goals_roadmap': 'Mục Tiêu & Lộ Trình',
    'nav.incidents': 'Sự Cố & Vấn Đề',
    'nav.scheduled_routines': 'Lịch Trình Hằng Ngày',
    'nav.audit_logs': 'Nhật Ký Hoạt Động',
    'nav.usage_costs': 'Chi Phí Sử Dụng',
    'nav.infrastructure': 'Cơ Sở Hạ Tầng',
    'nav.agents': 'Tác Nhân (Nhân Viên)',
    'nav.platform': 'Nền Tảng',
    'nav.credentials': 'Thông Tin Đăng Nhập',
    'nav.billing_packages': 'Nạp Tiền & Gói Cước',
    'nav.admin_panel': 'Bảng Quản Trị',
    'nav.sign_out': 'Đăng Xuất',
    'nav.workspace': 'Không Gian Làm Việc',
    'nav.architecture_studio': 'Xưởng Kiến Trúc',
    'nav.film_studio': 'Xưởng Phim',
    'nav.trading_studio': 'Xưởng Giao Dịch',
    'nav.exit_to_portal': 'Thoát Về Cổng Chính',
    'nav.loading': 'Đang tải...',
    'nav.no_fleets_found': 'Không tìm thấy hạm đội nào',

    // Incorporate Wizard
    'wizard.title': 'Triển Khai Hạm Đội AI',
    'wizard.subtitle': 'Cấu hình hạ tầng đám mây cho hạm đội, phân vai trò tác nhân và triển khai các máy ảo.',
    'wizard.step_1': 'Hạm Đội & Sứ Mệnh',
    'wizard.step_2': 'Cấu Hình Hạm Đội',
    'wizard.step_3': 'Nhiệm Vụ Đầu Tiên',
    'wizard.step_4': 'Xem Lại & Mật Khẩu',
    'wizard.company_name': 'Tên Hạm Đội',
    'wizard.company_domain': 'Tên Miền Hạm Đội',
    'wizard.mission_statement': 'Sứ Mệnh Hạm Đội',
    'wizard.mission_placeholder': 'Mô tả những gì hạm đội AI của bạn sẽ thực hiện...',
    'wizard.next': 'Bước Tiếp Theo',
    'wizard.previous': 'Quay Lại',
    'wizard.incorporating': 'Triển Khai Hạm Đội',
    'wizard.monthly_budget': 'Ngân Sách Chi Phí Sử Dụng Hằng Tháng',
    'wizard.initial_task_title': 'Tiêu Đề Nhiệm Vụ Đầu Tiên',
    'wizard.initial_task_desc': 'Mô Tả Nhiệm Vụ Đầu Tiên',
    'wizard.password': 'Mật Khẩu Chủ',
    'wizard.password_placeholder': 'Đặt mật khẩu bảo mật cho trang điều khiển',
    'wizard.summary_review': 'Kiểm Tra & Thành Lập',

    // Login Page
    'login.title': 'Đăng Nhập Vào Bihand',
    'login.subtitle': 'Nhập thông tin tài khoản để quản lý lực lượng lao động AI.',
    'login.email': 'Địa Chỉ Email',
    'login.password': 'Mật Khẩu',
    'login.button': 'Đăng Nhập',
    'login.no_account': 'Chưa có tài khoản? Vui lòng hoàn tất quy trình triển khai tại trang chủ.',

    // Dashboard General
    'dashboard.title': 'Hạm Đội Của Bạn',
    'dashboard.subtitle': 'Triển khai, mở rộng và quản lý hạ tầng đám mây cho các hạm đội tác nhân tự trị của bạn.',
    'dashboard.status.running': 'Đang Chạy',
    'dashboard.status.provisioning': 'Đang Khởi Tạo',
    'dashboard.status.stopped': 'Đã Dừng',
    'dashboard.no_fleets': 'Chưa có hạm đội nào hoạt động. Hãy bắt đầu bằng cách triển khai hạm đội đầu tiên của bạn.',

    // Additional translations
    'credentials.title': 'Quản lý thông tin đăng nhập',
    'credentials.subtitle': 'Lưu trữ thông tin đăng nhập và token để cấp quyền cho nhân viên AI.',
    'billing.title': 'Gói cước & Chi phí',
    'billing.subtitle': 'Mua thêm lượt sử dụng (Credits) để duy trì hoạt động cho nhân viên AI.',
    'billing.balance': 'Số dư tài khoản',
    'billing.purchase': 'Mua gói tín dụng',
    'fleet.org_chart.title': 'Sơ đồ tổ chức',
    'fleet.org_chart.subtitle': 'Xem cách các nhân viên AI làm việc và báo cáo công việc cho nhau.',
    'fleet.issues.title': 'Danh sách sự cố & nhiệm vụ',
    'fleet.issues.subtitle': 'Tạo các nhiệm vụ hoặc kiểm tra xem nhân viên AI nào đang giải quyết vấn đề.',
    'fleet.activity.title': 'Nhật ký trực tiếp',
    'fleet.activity.subtitle': 'Theo dõi thời gian thực các suy nghĩ và hoạt động của nhân viên AI.',
    'fleet.costs.title': 'Thống kê chi phí',
    'fleet.costs.subtitle': 'Thống kê hóa đơn và chi phí sử dụng API của toàn bộ hạm đội.',
    'dashboard.no_companies_found': 'Chưa tìm thấy hạm đội nào',
    'dashboard.no_companies_desc': 'Bạn chưa triển khai hạm đội AI nào. Hãy nhấp dưới đây để khởi chạy hạm đội tác nhân tự trị đầu tiên của mình.',
    'fleet.costs.infra_burn': 'Chi phí máy ảo',
    'fleet.costs.api_spend': 'Chi phí API',
    'fleet.costs.limit': 'Giới hạn',

    // SANT Arch Studio
    'arch.title': 'Phòng Thiết Kế',
    'arch.subtitle': 'Hệ sinh thái dựng hình AI, cải tạo nội thất và quy phim kiến trúc tối tân hàng đầu.',
    'arch.balance': 'Ví Bihand',
    'arch.rendered_image': 'Màn hình xem trước bản dựng',
    'arch.rendering_ready': 'Sẵn sàng dựng hình AI',
    'arch.rendering_ready_desc': 'Tải lên hình ảnh hoặc chọn mẫu để bắt đầu',
    'arch.start_render': 'Bắt đầu kết xuất',
    'arch.back': 'Quay lại',
    'arch.sketch': '1. Tải lên hình ảnh phác thảo',
    'arch.sketch_desc': 'Định dạng hỗ trợ PNG, JPG, JPEG',
    'arch.add_sketch': 'Thêm ảnh phác thảo',
    'arch.prompt': 'Ý Tưởng Thiết Kế:',
    'arch.prompt_placeholder': 'Nhập mô tả ý tưởng thiết kế...',
    'arch.details': '3. Cấu hình chi tiết',
    'arch.building_type': 'Loại công trình:',
    'arch.style': 'Phong cách kết xuất:',
    'arch.aspect_ratio': 'Tỷ Lệ Khung Hình',
    'arch.negative_prompt': 'Ý Tưởng Loại Bỏ',
    'arch.history': 'Lịch sử kết xuất gần đây',
    'arch.no_history': 'Chưa có lịch sử kết xuất nào.',
    'arch.load_more': 'Tải thêm lịch sử',
    'arch.submitting': 'Đang gửi yêu cầu...',

    // Film Studio
    'film.title': 'Phòng Dựng Phim',
    'film.subtitle': 'Hệ sinh thái dựng phim AI, truyện tranh, hoạt hình giáo dục và âm thanh chất lượng phòng thu.',
    'film.start_film': 'Bắt đầu làm phim',
    'film.submitting': 'Đang tiến hành dựng phim...',
    'film.create_project': 'Tạo dự án mới',
    'film.project_name': 'Tên dự án',
    'film.wallet': 'Ví',
    'film.empty_project': 'Bạn chưa khởi tạo dự án dựng phim nào',
    'film.create_first': 'Tạo dự án đầu tiên',
    'film.delete_project': 'Xóa dự án',
    'film.nodes': 'Phân cảnh',
    'film.untitled': 'Dự án không tên',
    'film.history_title': 'Lịch sử kết xuất & Mẫu AI',
    'film.use_template': 'Dùng mẫu AI',
    'film.open_project': 'Mở dự án',
    'film.no_history': 'Chưa có lịch sử kết xuất thành công nào. Hãy tạo một dự án mới và chạy AI import!',
    'film.cost': 'Chi phí',
    'film.quick_video_gen': 'Tạo Video AI nhanh',
    'film.import_title': 'Nhập tư liệu thông minh (AI Import)',
    'film.add_sketch': 'Hình ảnh phác thảo (Tùy chọn):',
    'film.add_ref': 'Thêm reference',
    'film.prompt_label': 'Ý tưởng kịch bản (Prompt):',
    'film.style_label': 'Phong cách (Art Style):',
    'film.aspect_ratio_label': 'Tỷ lệ khung hình:',
    'film.voice_label': 'Giọng nói AI Narrator:',
    'film.locale_label': 'Ngôn ngữ đọc:',
    'film.sections_label': 'Số lượng phân cảnh muốn chèn:',
    'film.cancel': 'Hủy bỏ',
    'film.confirm_import': 'Xác nhận import mới',
    'film.choose_from_history': 'Chọn tư liệu từ lịch sử AI (Lịch sử)',
    'film.import_all': 'Nhập Tất cả',
    'film.empty_history_desc': 'Lịch sử tư liệu trống. Vui lòng tạo bản dựng AI mới ở thanh bên trái.',

    // Tab translations (Vietnamese)
    'film.tab.comic': 'Truyện Tranh',
    'film.tab.vlog': 'Dựng Phim',
    'film.tab.manim': 'Hoạt Hình',
    'film.tab.image': 'Tạo Ảnh',
    'film.tab.sound': 'Âm Thanh',
    
    'arch.tab.render_img': 'Render Ảnh',
    'arch.tab.render_plan': 'Render Mặt Bằng',
    'arch.tab.renovate': 'Cải Tạo AI',
    'arch.tab.view_sync': 'Đồng Bộ View'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('bihand_language');
    return (saved === 'en' || saved === 'vi') ? saved : 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('bihand_language', lang);
  };

  const t = (key: string, defaultValue?: string): string => {
    const translation = translations[language]?.[key];
    if (translation !== undefined) {
      return translation;
    }
    // Fallback to English translation
    const fallback = translations['en']?.[key];
    if (fallback !== undefined) {
      return fallback;
    }
    return defaultValue || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
